import { Inter } from 'next/font/google'
import classNames from "classnames";

import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import {StoreProvider} from "@/store/StoreProvider";

import styles from "./styles.module.css";
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const bodyStyles = classNames(inter.className, styles.container)

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bodyStyles}>
      <StoreProvider>
        <Header/>
        <div className={styles.content}>
          {children}
        </div>
        <Footer/>
      </StoreProvider>
      </body>
    </html>
  )
}
